marketing_and_production_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mcdonalds/', include('mcdonalds.urls'),),
]

mcdonalds/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('stores_contact/',views.stores_contact, name='stores_contact'),
    path('stores_contact/add/', views.add_stores_contact, name='add_stores_contact'),
    path('stores_contact/update/<int:store_id>/', views.update_stores_contact, name='update_stores_contact'),
    path('stores_contact/delete/<int:store_id>/', views.delete_stores_contact, name='delete_stores_contact'),
    path('suppliers_contact/',views.suppliers_contact, name='suppliers_contact'),
    path('suppliers_contact/add/', views.add_suppliers_contact, name='add_suppliers_contact'),
    path('suppliers_contact/update/<int:supplier_id>/', views.update_suppliers_contact, name='update_suppliers_contact'),
    path('suppliers_contact/delete/<int:supplier_id>/', views.delete_suppliers_contact, name='delete_suppliers_contact'),
    path('raw_materials/als_predict/',views.raw_materials_predict, name='raw_materials_predict'),
    path('raw_materials_order/',views.raw_materials_order, name='raw_materials_order'),
    path('raw_materials/',views.raw_materials, name='raw_materials'),
    path('strategies_list/', views.strategies_list, name='strategies_list'),
    path('strategy/store/', views.store_strategy, name='store_strategy'),
    # path('strategy/update/<int:strategy_id>/', views.update_strategy, name='update_strategy'),
    path('strategy/delete/<int:strategy_id>/', views.delete_strategy, name='delete_strategy'),
    path('strategy_prod/delete/<int:spr_id>', views.delete_spr, name='delete_spr'),
    path('products/<int:prod_category_num>', views.search_prod_by_category, name='search_prod_by_category'),
    # path('customer_rel/binary_tree/', views.binary_tree, name='binary_tree'),
    path('customer_rel/survival_rate/', views.survival_rate, name='survival_rate'),
    path('customer_rel/rfm/', views.rfm, name='rfm'),
    path('customer_rel/rfm/<int:rfm_id>', views.customer, name='customer'),
    path('edit/<int:material_id>/', views.get_edit_page, name='get_edit_page'),
    path('update/<int:material_id>/', views.save_update_raw_materials, name='save_update_raw_materials'),
    path('send_store_demend', views.receive_store_demand, name='receive_store_demand'),
    #path('go_to_store_send_demand_page',views.go_to_store_send_demand_page, name='go_to_store_send_demand_page'),
    path('orders/add/', views.add_order, name='add_order'),
    path('store_demand/', views.store_demand, name='store_demand'),
    path('store_demand_detail/<int:store_demand_id>', views.store_demand_detail, name='store_demand_detail'),
    path('raw_material_arrived_store/<int:store_demand_id>', views.raw_material_arrived_store, name='raw_material_arrived_store'),
    path('raw_material_arrived_center/<int:order_id>', views.raw_material_arrived_center, name='raw_material_arrived_center'),
    path('login/', views.sign_in, name='Login'),
    path('marketing_dashboard/', views.marketing_dashboard, name='marketing_dashboard'),
    path('marketing_dashboard_windows', views.marketing_dashboard_windows, name='marketing_dashboard_windows'),
]
app_name='mcdonalds'

nccu_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accountingsystem/', include('accountingsystem.urls')),
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mcdonalds/models.py
from django.db import models
from datetime import date
from django.core.validators import MinValueValidator, MaxValueValidator
from model_utils import Choices
from django.utils.translation import ugettext_lazy  as _

##################################### 資料來源為其他部門的 tables
class Sales(models.Model):
    '''行銷相關，資料來源：其他部門。'''
    sales_id = models.AutoField(primary_key=True)
    date = models.DateField() # 只需要其中的 year, month
    numbers = models.PositiveIntegerField() # 數量
    amount = models.PositiveIntegerField() # 金額
    # FK Products, Stores
    product = models.ForeignKey('Products', on_delete=models.CASCADE)
    store = models.ForeignKey('Stores', on_delete=models.CASCADE)
    class Meta:
        db_table = 'sales'

class RFM(models.Model):
    rfm_id = models.SmallAutoField(primary_key=True)
    actual_resp_rate = models.SmallIntegerField(validators=[MaxValueValidator(100)]) # 實際回應率最高 100, 可為負數
    rfm_value = models.PositiveSmallIntegerField()

class Customers(models.Model):
    '''顧客資訊，資料來源：其他部門。'''
    GENDER = Choices(
        (0, 'FEMALE', _('FEMALE')),
        (1, 'MALE', _('MALE'))
    )
    cid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    gender = models.IntegerField(choices = GENDER)
    email = models.EmailField(max_length=30, blank=True, null=True)
    # FK RFM
    rfm = models.ForeignKey('RFM', on_delete=models.CASCADE)

    class Meta:
        db_table = 'customers'

class ShoppingRecords(models.Model):
    '''顧客消費紀錄，資料來源：其他部門'''
    sr_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=30) # 商品名稱
    amount = models.PositiveSmallIntegerField() # 消費金額
    shopping_date = models.DateField() # 消費日
    snackes = models.TextField(blank=True) # 配餐，不同名稱用 , 分割
    # FK Customers
    customer = models.ForeignKey('Customers', on_delete=models.CASCADE)

    class Meta:
        db_table = 'shopping_records'

##################################### 屬於我們系統的 tables.
class MarketingStrategies(models.Model):
    '''行銷策略'''
    STRATEGY_STATUS = Choices(
        (0, 'ENABLED', _('ENABLED')),
        (1, 'DISABLED', _('DISABLED'))
    )
    strategy_id = models.AutoField(primary_key=True)
    start_date = models.DateField(default=date.today) # 預設策略開始日期是當天
    end_date = models.DateField()
    status = models.IntegerField(choices=STRATEGY_STATUS, default=STRATEGY_STATUS.ENABLED) # 預設是策略有效
    strategy_name = models.CharField(max_length=30) # 策略名稱
    description = models.TextField(blank=True) # 策略內容，允許為空白

    class Meta:
        ordering = ['status', 'start_date', 'end_date']
        db_table = 'marketing_strategies'


class Products(models.Model):
    '''商品 (eg. 雙層牛肉吉事堡)'''
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=30) # 商品名稱
    amount = models.PositiveSmallIntegerField() # 商品售價
    category = models.CharField(blank=True, max_length=10) # 商品類別
    class Meta:
        db_table = 'products'

class RawMaterial(models.Model):
    '''原物料'''
    material_id = models.AutoField(primary_key=True)
    material_name = models.CharField(max_length=30) # 原物料名稱
    amount = models.PositiveIntegerField() # 原物料售價
    security_numbers = models.PositiveIntegerField() # 安全存量
    quantity = models.PositiveIntegerField() # 經濟訂購量
    reorder_point = models.PositiveIntegerField() # 再訂購點
    consumption_rate = models.PositiveIntegerField() # 消耗速度：N / 天(期間)
    lead_time = models.PositiveSmallIntegerField() # 前置時間：天數
    expiration_duration = models.PositiveSmallIntegerField() # 有效期間：天數
    on_hand_inventory = models.PositiveIntegerField() # 現有庫存
    # FK Suppliers
    supplier = models.ForeignKey('Suppliers', on_delete=models.CASCADE)
    class Meta:
        db_table = 'raw_material'
    def __unicode__(self):
        return '%s' % self.material_name
    
    def __str__(self):
        return self.material_name

class StrategyProductRel(models.Model):
    '''行銷策略與商品之間的關係'''
    spr_id = models.AutoField(primary_key = True)
    numbers = models.PositiveSmallIntegerField() # 此一"行銷策略"下所需的"商品"數
    # FK Products, Strategy
    product = models.ForeignKey('Products', on_delete=models.CASCADE)
    strategy = models.ForeignKey('MarketingStrategies', on_delete=models.CASCADE)
    class Meta:
        db_table = 'strategy_product_rel'

class ProductMaterialRel(models.Model):
    '''商品與原物料之間的關係'''
    pmr_id = models.AutoField(primary_key=True)
    numbers = models.PositiveSmallIntegerField() # 此一"商品"需要多少個這種"原物料"
    # FK Products, RawMaterial
    product = models.ForeignKey('Products', on_delete=models.CASCADE)
    material = models.ForeignKey('RawMaterial', on_delete=models.CASCADE)
    class Meta:
        db_table = 'product_material_rel'

class StoreDemand(models.Model):
    '''門市需求單'''
    DEMAND_STATUS = Choices(
        (0, 'RECEIVED', _('RECEIVED')), # 接收到門市需求單
        (1, 'ARRIVAL', _('ARRIVAL'))   # 原物料已到門市（完成需求單）
    )
    store_demand_id = models.AutoField(primary_key=True)
    created_date = models.DateField(default=date.today)
    status = models.PositiveSmallIntegerField(choices=DEMAND_STATUS, default=DEMAND_STATUS.RECEIVED) # 需求單狀態
    # FK Store
    store = models.ForeignKey('Stores', on_delete=models.CASCADE,db_constraint=False)

    class Meta:
        ordering = ['created_date', 'status']
        db_table = 'store_demand'

class StoreDemandDetails(models.Model):
    '''門市需求單內容'''
    store_demand_details_id = models.AutoField(primary_key=True)
    prod_numbers = models.PositiveSmallIntegerField( blank=True, null=True) # 所需商品數量
    # FK RawMaterial, Stores
    product = models.ForeignKey('Products', on_delete=models.CASCADE,db_constraint=False)
    store_demand = models.ForeignKey('StoreDemand', on_delete=models.CASCADE, blank=True, null=True,db_constraint=False) # TODO 不知道為什麼這裡它要預設值或者要允許 null

    class Meta:
        db_table = 'store_demand_details'

class MarketingData(models.Model):
    '''行銷數據，資料來源：由我們系統算出結果後存入。'''
    md_id = models.AutoField(primary_key=True)
    date = models.DateField() # 只需要其中的 year, month
    cvr = models.DecimalField(max_digits=5, decimal_places=2)
    breakeven_rate = models.DecimalField(max_digits=5, decimal_places=2) # 損益平衡率
    survival_rate = models.PositiveSmallIntegerField(validators=[MinValueValidator(0),
                                                                     MaxValueValidator(100)]) # 存活率
    class Meta:
        db_table = 'marketing_data'

class Suppliers(models.Model):
    '''供應商'''
    supplier_id = models.AutoField(primary_key=True)
    supplier_name = models.CharField(max_length=30) # 供應商名稱
    supplier_address = models.CharField(max_length=255) # 供應商地址
    supplier_phone = models.CharField(max_length=30) # 供應商電話，存成 CharField

    class Meta:
        db_table = 'suppliers'

class Orders(models.Model):
    '''訂單（與上游供應商之間的）'''
    ORDER_STATUS = Choices(
        (0, 'ESTABLISHED', _('ESTABLISHED')), # 建立訂單，已交給上游供應商
        (1, 'ARRIVAL', _('ARRIVAL'))      # 原物料已到配送中心
    )
    order_id = models.AutoField(primary_key=True)
    order_date = models.DateField(default=date.today) # 下訂日期，預設是當天
    status = models.PositiveSmallIntegerField(choices=ORDER_STATUS, default=ORDER_STATUS.ESTABLISHED) # 訂單狀態
    order_amount = models.PositiveIntegerField() # 訂購數量
    # FK RawMaterial
    material = models.ForeignKey('RawMaterial', on_delete=models.CASCADE)

    class Meta:
        ordering = ['order_date', 'status']
        db_table = 'orders'

class Stores(models.Model):
    '''門市'''
    store_id = models.AutoField(primary_key = True)
    store_name = models.CharField(max_length=30) # 門市名稱
    store_address = models.CharField(max_length=255) # 門市地址
    store_phone = models.CharField(max_length=30) # 門市電話，存成 CharField
    store_region = models.CharField(blank=True, max_length=2) # 門市地區
    class Meta:
        db_table = 'stores'

mcdonalds/forms.py
from datetime import date

from django import forms
from model_utils import Choices

from .models import RawMaterial, MarketingStrategies, Orders, Stores, Suppliers


class RawMaterialModelForm(forms.ModelForm):
    class Meta:
        model = RawMaterial
        fields = ('material_id','material_name', 'amount','on_hand_inventory','security_numbers')
        widgets = {
            'material_id': forms.TextInput(attrs={'class': 'form-control'}),
            'material_name': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'on_hand_inventory': forms.NumberInput(attrs={'class': 'form-control'}),
            'security_numbers': forms.NumberInput(attrs={'class': 'form-control'})

        }
        # labels = {
        #     'material_name': '原物料名稱',
        #     'amount': '單位成本',
        #     'on_hand_inventory': '庫存',
        #     'security_numbers':'安全存量'
        # }

class MarketingStrategyForm(forms.ModelForm):

    # product_json = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mx-sm-3', 'type': 'hidden', 'name': 'product_list'}))

    class Meta:
        model = MarketingStrategies
        fields = ('strategy_name', 'description', 'start_date', 'end_date', 'status')
        STRATEGY_STATUS = Choices(
            (0, 'ENABLED'),
            (1, 'DISABLED')
        )
        widgets = {
            # 'strategy_id': forms.NumberInput(attrs= {'class': 'form-control'}),
            'strategy_name': forms.TextInput(attrs = {'class': 'form-control mx-sm-3', 'name': 'strategy_name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'name': 'description', 'rows': 3}),
            'start_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control datepicker mx-sm-3', 'name':'start_date'}),
            'end_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control datepicker mx-sm-3', 'name': 'end_date'}),
            'status': forms.Select(attrs = {'class': 'form-control mx-sm-3', 'name': 'status'}, choices=STRATEGY_STATUS),

        }


class OrderForm(forms.ModelForm):
    
    class Meta:
        model = Orders
        fields = {'order_amount','material','order_date'}
        ORDER_STATUS = Choices(
            (0, '~'),
            (1, '大麥克麵包222'),
            (2, '1/10牛肉餅'),
            (3, '吉士片'),
            (4, '切片生菜'),
            (5, '大麥克醬'),
            (6, '布里歐麵包'),
            (7, '番茄片'),
            (8, '厚切培根'),
            (9, '安格斯牛肉餅'),
            (10, 'BLT燒烤醬'),
            (11, '番茄醬'),
            (12, '薯條'),
            (13, '麥克雞塊'),
            (14, '可樂'),

        )
        widgets = {
            'order_amount': forms.TextInput(attrs={'class': 'form-control'}),
            'material': forms.Select(attrs = {'class': 'form-control'}, choices=ORDER_STATUS),
            #forms.Select(attrs = {'class': 'form-control'}, choices=ORDER_STATUS),
            #choices=RawMaterial.objects.all().values_list('material_id', 'material_name'),
            'order_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control datepicker'}),
        }
        labels = {
            'order_amount':'訂購數量',
            'material':'訂購商品',
            'order_date':'訂購日期'
        }

class StoresContactForm(forms.ModelForm):
    class Meta:
        model = Stores
        fields = ('store_name', 'store_address', 'store_phone', 'store_region')
        widgets = {
            # 'strategy_id': forms.NumberInput(attrs= {'class': 'form-control'}),
            'store_name': forms.TextInput(attrs = {'class': 'form-control'}),
            'store_address': forms.TextInput(attrs={'class': 'form-control'}),
            'store_phone': forms.TextInput(attrs={'class': 'form-control'}),
            'store_region':  forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            'store_name': '分店名稱',
            'store_address': '地址',
            'store_phone': '連絡電話',
            'store_region': '區域',
        }

class SuppliersContactForm(forms.ModelForm):
    class Meta:
        model = Suppliers
        fields = ('supplier_name', 'supplier_address', 'supplier_phone')
        widgets = {
            # 'strategy_id': forms.NumberInput(attrs= {'class': 'form-control'}),
            'supplier_name': forms.TextInput(attrs = {'class': 'form-control'}),
            'supplier_address': forms.TextInput(attrs={'class': 'form-control'}),
            'supplier_phone': forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            'supplier_name': '供應商名稱',
            'supplier_address': '地址',
            'supplier_phone': '連絡電話',
        }


class LoginForm(forms.Form):
    username = forms.CharField(
        label="帳號",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label="密碼",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

templates/mcdonalds/index.html
{% extends "base.html" %}

{% block title %} index {% endblock title %}

{% block content %}
    <h1 class="col-md-12">歡迎登入！</h1>
    
    <div class="col-md-12">


    </div>

{% endblock content %}

templates/mcdonalds/raw_material.html
{% extends "base.html" %}

{% block title %}原物料庫存{% endblock title %}

{% block content %}


<div class="col-md-12">
 
    <!-- <input type="button" value="原物料訂購預估" onclick="location.href='raw_materials_predict'">
    <input type="button" value="原物料實際訂購單" onclick="location.href='要前往的網頁連結'">
    <h4>原物料訂購預估</h4> -->
    <div class="row">
    <h4 class="col-md-10">原物料庫存</h4>
    <div class="col-md-2" style='float:right;'>
        <a class="btn " href="{% url 'mcdonalds:add_order' %}" role="button" style="background-color: #ffd480;">新增原物料訂單</a>
    </div>
    </div>
    <br>
    <br>
    <table class="table table-bordered table-striped" data-toggle="table">
        <thead style="background-color:  #7d7d7c;">
            <tr>
                <th data-sortable="true"><span style="color:white;">原物料ID</span></th>
                <th><span style="color:white;">原物料名稱</span></th>
                <th data-sortable="true"><span style="color:white;">單位成本</span></th>
                <th data-sortable="true"><span style="color:white;">庫存</span></th>
                <th data-sortable="true"><span style="color:white;">安全存量</span></th>
                <th data-sortable="true"><span style="color:white;">經濟訂購量</span></th>
                <th data-sortable="true"><span style="color:white;">再訂購點</span></th>
                <th data-sortable="true"><span style="color:white;">供應商</span></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for raw_material in raw_materials %}
                <tr>
                    <td>{{ raw_material.material_id }}</td>
                    <td>{{ raw_material.material_name }}</td>
                    <td>{{ raw_material.amount }}</td>
                    <td>{{ raw_material.on_hand_inventory }}</td>
                    <td>{{ raw_material.security_numbers }}</td>
                    <td>{{ raw_material.quantity }}</td>
                    <td>{{ raw_material.reorder_point }}</td>
                    <td>{{ raw_material.supplier_name }}</td>
                    <td>
                        <a href="{% url 'mcdonalds:get_edit_page' material_id=raw_material.material_id %}" class="btn" style="background-color: #ffd480;">修改</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


</div>

{% endblock content %}

templates/mcdonalds/raw_material_predict.html
{% extends "base.html" %}

{% block title %}原物料訂購預估{% endblock title %}

{% block content %}


<div class="col-md-12">
    <br>
    <div class="btn-group" role="group" aria-label="Basic example">
        <button id="rawmaterialspredict" type="button" class="btn btn-dark" onclick="location.href='{% url 'mcdonalds:raw_materials_predict' %}'">原物料訂購預估</button>
        <button id="rawmaterialsorder" type="button" class="btn btn-light" onclick="location.href='{% url 'mcdonalds:raw_materials_order' %}'">原物料實際訂購單</button>
    </div>

   <br>
   <br>
   <br>
 
    <!-- <input type="button" value="原物料訂購預估" onclick="location.href='raw_materials_predict'">
    <input type="button" value="原物料實際訂購單" onclick="location.href='要前往的網頁連結'">
    <h4>原物料訂購預估</h4> -->
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered">
            <thead style="background-color:  #7d7d7c;">
                <th><span style="color:white;">原物料名稱</span></th>
                <th><span style="color:white;">經濟訂購量</span></th>
                <th><span style="color:white;">再訂購點</span></th>
            </thead>
            <tbody>
            {% for raw_material_predict in raw_materials_predict %}  

                <tr>
                    <td>{{ raw_material_predict.material_name }}</td> 
                    <td>{{ raw_material_predict.quantity }}</td>
                    <td>{{ raw_material_predict.reorder_point }}</td>
                </tr>  
            {% endfor %} 
            </tbody>
        </table>
	</div>
</div>
<!-- 
<script>
    $("#rawmaterialspredict").click(function() {
    alert( "!" );
    $("#raw_materials_predict").removeClass("btn btn-light");
    $("#rawmaterialspredict").addClass("btn btn-dark");
    alert( "!" );
    });
</script> -->

{% endblock content %}

templates/mcdonalds/raw_materials_order.html
{% extends "base.html" %}

{% block title %}原物料實際訂購單{% endblock title %}

{% block content %}


<div class="col-md-12">
    <div class="col-md-12">
        <br>
        <h4>原物料訂單</h4>
    </div>
    <div class="btn-group" role="group" aria-label="Basic example">
        <button id="rawmaterialspredict" type="button" class="btn btn-light" onclick="location.href='{% url 'mcdonalds:raw_materials_predict' %}'">原物料訂購預估</button>
        <button id="rawmaterialsorder" type="button" class="btn btn-dark" onclick="location.href='{% url 'mcdonalds:raw_materials_order' %}'">原物料實際訂購單</button>
    </div>
    <div class="col-md-2" style='float:right;'>
        <a class="btn " href="{% url 'mcdonalds:add_order' %}" role="button" style="background-color: #ffd480;">新增原物料訂單</a>
    </div>

   <br>
   <br>
   <br>

    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered">
            <thead style="background-color:  #7d7d7c;">
                <th><span style="color:white;">訂單ID</span></th>
                <th><span style="color:white;">原物料名稱</span></th>
                <th><span style="color:white;">訂購量</span></th>
                <th><span style="color:white;">下訂日期</span></th>
                <th><span style="color:white;">訂單狀態</span></th>
            </thead>
            <tbody>

            {% for raw_material_order in raw_materials_order %}  
                <tr>
                    <td>{{ raw_material_order.order_id }}</td> 
                    <td>{{ raw_material_order.material_name }}</td> 
                    <td>{{ raw_material_order.order_amount }}</td>
                    <td>{{ raw_material_order.order_date }}</td>
                    <td>{{ raw_material_order.status }}</td>
                </tr>  
            {% endfor %} 
            </tbody>
        </table>
	</div>
</div>


{% endblock content %}

templates/mcdonalds/stores_contact.html
{% extends "base.html" %}

{% block title %}通訊錄{% endblock title %}

{% block content %}

<div class="col-md-12">
    <h4>通訊錄</h4>
    <br>
    <div class="row">
        <div class="col-md-11">
            <div class="btn-group" role="group" aria-label="Basic example">
                <button id="suppliers_contact" type="button" class="btn btn-light" onclick="location.href='{% url 'mcdonalds:suppliers_contact' %}'">供應商</button>
                <button id="stores_contact" type="button" class="btn btn-dark" onclick="location.href='{% url 'mcdonalds:stores_contact' %}'">分店</button>
            </div>
        </div>
        <div class="col-md-1">
            <a class="btn" href="{% url 'mcdonalds:add_stores_contact' %}" role="button"style="background-color: #ffd480;">新增</a>
        </div>
    </div>
</div>
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered">
        <thead style="background-color:  #7d7d7c;">
            <tr>
                <th><span style="color:white;">分店名稱</span></th>
                <th><span style="color:white;">地址</span></th>
                <th><span style="color:white;">連絡電話</span></th>
                <th><span style="color:white;">所在區域</span></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for store in store %}
            <tr>
                <td>{{ store.store_name }}</td>
	            <td>{{ store.store_address }}</td>
	            <td>{{ store.store_phone }}</td>
                <td>{{ store.store_region }}</td>
                <td>
                    <a href="{% url 'mcdonalds:update_stores_contact' store_id=store.store_id %}" class="btn"style="background-color: #ffd480;">修改</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

templates/mcdonalds/stores_contact_detail.html
{% extends "base.html" %}

{% block title %} 通訊錄詳細資訊 {% endblock title %}

{% block extra_css %}
    <style type="text/css">
        .hidden{
            display: none;
        }
    </style>
{% endblock %}

{% block content %}
    {% if isAdded %}
        <div id="popup" class="col-md-10 offset-1 alert alert-success alert-dismissible fade show col-md-8">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>成功!</strong> 指定操作成功提示信息。
        </div>
    {% endif %}

    <h1 class="col-md-12">通訊錄詳細資訊</h1>
    <div class="col-md-12">
        {% if form and store_id %}
            <form action="{% url 'mcdonalds:update_stores_contact' store_id=store_id %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-group col-md-6">

                        {{ form }}

                        <input class="btn btn-success" type="submit" value="儲存" />
                    </div>
                </div>
            </form>
            <a class="btn btn-primary btn-light" href="{% url 'mcdonalds:delete_stores_contact' store_id=store_id %}" role="button">刪除</a>
        {% else %}
            <form action="{% url 'mcdonalds:add_stores_contact'%}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-group col-md-6">

                        {{ form }}

                        <input class="btn btn-success" type="submit" value="確認新增" />
                    </div>
                </div>
            </form>
        {% endif %}
    </div>

{% endblock content %}


{% block extra_scripts %}
    <script type="text/javascript">
        $('#popup').removeClass("hidden")
        $(".close").on('click', function() {
            $('#popup').addClass("hidden")
        })
    </script>
{% endblock %}

templates/mcdonalds/suppliers_contact.html
{% extends "base.html" %}

{% block title %}通訊錄{% endblock title %}

{% block content %}

<div class="col-md-12">
<div class="col-md-12">
    <h4>通訊錄</h4>
    <br>
    <div class="row">
        <div class="col-md-9">
            <div class="btn-group" role="group" aria-label="Basic example">
                <button id="suppliers_contact" type="button" class="btn btn-dark" onclick="location.href='{% url 'mcdonalds:suppliers_contact' %}'">供應商</button>
                <button id="stores_contact" type="button" class="btn btn-light" onclick="location.href='{% url 'mcdonalds:stores_contact' %}'">分店</button>
            </div>
        </div>
    </div>
</div>
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered">
        <thead style="background-color:  #7d7d7c;">
            <tr>
                <th><span style="color:white;">供應商名稱</span></th>
                <th><span style="color:white;">地址</span></th>
                <th><span style="color:white;">連絡電話</span></th>
                <th><span style="color:white;">供應原料</span></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for supplier in suppliers %}
            <tr>
                <td>{{ supplier.supplier_name }}</td>
	            <td>{{ supplier.supplier_address }}</td>
	            <td>{{ supplier.supplier_phone }}</td>
                <td>{{ supplier.material_name }}</td>
                <td>
                    <a href="{% url 'mcdonalds:update_suppliers_contact' supplier_id=supplier.supplier_id %}" class="btn "style="background-color: #ffd480;">修改</a>
                </td>
             </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}