marketing_and_production_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mcdonalds/', include('mcdonalds.urls'),),
]

mcdonalds/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('stores_contact/',views.stores_contact, name='stores_contact'),
    path('stores_contact/add/', views.add_stores_contact, name='add_stores_contact'),
    path('stores_contact/update/<int:store_id>/', views.update_stores_contact, name='update_stores_contact'),
    path('stores_contact/delete/<int:store_id>/', views.delete_stores_contact, name='delete_stores_contact'),
    path('suppliers_contact/',views.suppliers_contact, name='suppliers_contact'),
    path('suppliers_contact/add/', views.add_suppliers_contact, name='add_suppliers_contact'),
    path('suppliers_contact/update/<int:supplier_id>/', views.update_suppliers_contact, name='update_suppliers_contact'),
    path('suppliers_contact/delete/<int:supplier_id>/', views.delete_suppliers_contact, name='delete_suppliers_contact'),
    path('raw_materials/als_predict/',views.raw_materials_predict, name='raw_materials_predict'),
    path('raw_materials_order/',views.raw_materials_order, name='raw_materials_order'),
    path('raw_materials/',views.raw_materials, name='raw_materials'),
    path('strategies_list/', views.strategies_list, name='strategies_list'),
    path('strategy/store/', views.store_strategy, name='store_strategy'),
    # path('strategy/update/<int:strategy_id>/', views.update_strategy, name='update_strategy'),
    path('strategy/delete/<int:strategy_id>/', views.delete_strategy, name='delete_strategy'),
    path('strategy_prod/delete/<int:spr_id>', views.delete_spr, name='delete_spr'),
    path('products/<int:prod_category_num>', views.search_prod_by_category, name='search_prod_by_category'),
    # path('customer_rel/binary_tree/', views.binary_tree, name='binary_tree'),
    path('customer_rel/survival_rate/', views.survival_rate, name='survival_rate'),
    path('customer_rel/rfm/', views.rfm, name='rfm'),
    path('customer_rel/rfm/<int:rfm_id>', views.customer, name='customer'),
    path('edit/<int:material_id>/', views.get_edit_page, name='get_edit_page'),
    path('update/<int:material_id>/', views.save_update_raw_materials, name='save_update_raw_materials'),
    path('send_store_demend', views.receive_store_demand, name='receive_store_demand'),
    #path('go_to_store_send_demand_page',views.go_to_store_send_demand_page, name='go_to_store_send_demand_page'),
    path('orders/add/', views.add_order, name='add_order'),
    path('store_demand/', views.store_demand, name='store_demand'),
    path('store_demand_detail/<int:store_demand_id>', views.store_demand_detail, name='store_demand_detail'),
    path('raw_material_arrived_store/<int:store_demand_id>', views.raw_material_arrived_store, name='raw_material_arrived_store'),
    path('raw_material_arrived_center/<int:order_id>', views.raw_material_arrived_center, name='raw_material_arrived_center'),
    path('login/', views.sign_in, name='Login'),
    path('marketing_dashboard/', views.marketing_dashboard, name='marketing_dashboard'),
    path('marketing_dashboard_windows', views.marketing_dashboard_windows, name='marketing_dashboard_windows'),
]
app_name='mcdonalds'

nccu_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accountingsystem/', include('accountingsystem.urls')),
    path('admin/', admin.site.urls),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>  
<html lang="zh-Hant">
<head>  
<meta charset="UTF-8">
{% load static %}
<title>{% block title %}{% endblock %}</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {#<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>#}
<!-- modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
<!-- FontAwesome -->
<script src="https://kit.fontawesome.com/5dc39887b7.js" crossorigin="anonymous"></script> 

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">
<!--table sort-->
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.css">
<script src="https://unpkg.com/bootstrap-table@1.18.1/dist/bootstrap-table.min.js"></script>

{% block extra_css %}
    <style>
    nav {
        margin-bottom: 20px;
    }
    </style>
{% endblock %}

{% block extra_reference_link %}

{% endblock %}
</head> 
<body>
    
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #FCFF9D;height: 80px;font-size: 1.4em">
    <a class="navbar-brand" href="#">
        <img src="https://resource01-proxy.ulifestyle.com.hk/res/v3/image/content/2275000/2276895/Mcdonalds-Logo-PNG-Transparent-Image_1024.png" alt="Logo" style="width:60px;">
    </a>
	<a class="navbar-brand" href="#"></a>
		<div class="collapse navbar-collapse">
		    <ul class="navbar-nav mr-auto">
                {# TODO 之後要修改擺放的位置，eg. 點選行銷只會有行銷相關的出來#}
                <!-- 行銷相關 -->
                
                <li class="nav-item">
		            <a class="nav-link" href="{% url 'mcdonalds:marketing_dashboard' %}" tabindex="-1" aria-disabled="true" >行銷 Dashboard</a>
                 </li>
                 &nbsp&nbsp&nbsp
                
                <li class="nav-item">
                    <!-- 顧客關係管理預設是二元樹 -->
		            <a class="nav-link" href="{% url 'mcdonalds:survival_rate' %}" tabindex="-1" aria-disabled="true">顧客關係管理</a>
                 </li>
                 &nbsp&nbsp&nbsp
                <li class="nav-item">
		            <a class="nav-link" href="{% url 'mcdonalds:strategies_list' %}"  aria-disabled="true">行銷策略列表</a>
                 </li>
                 &nbsp&nbsp&nbsp
                <!-- 作業管理相關 -->
		        <li class="nav-item">
		            <a class="nav-link" href="{% url 'mcdonalds:raw_materials' %}" tabindex="-1" aria-disabled="true">原物料庫存</a>
                 </li>
                 &nbsp&nbsp&nbsp
		         <li class="nav-item dropdown">
		            <a class="nav-link" href="{% url 'mcdonalds:store_demand' %}" tabindex="-1" aria-disabled="true">門市需求單</a>
                 </li>
                 &nbsp&nbsp&nbsp
		         <li class="nav-item dropdown">
		            <a class="nav-link" href="{% url 'mcdonalds:raw_materials_order' %}" tabindex="-1" aria-disabled="true">原物料訂單</a>
                 </li>
                 &nbsp&nbsp&nbsp
		         <li class="nav-item">
		            <a class="nav-link" href="{% url 'mcdonalds:suppliers_contact' %}" tabindex="-1" aria-disabled="true">通訊錄</a>
		         </li>
		    </ul>
		</div>
</nav>
<br>
<div class="container">
 <div class="row">
    {% block content %}{% endblock %}
 </div>
</div>
    <script type="text/javascript">

    $(document).ready(function() {
        $('#bootstrapdatatable').DataTable({
          "aLengthMenu": [[ 5, 10, 25, -1], [ 5, 10, 25, "All"]],
            "iDisplayLength": 5
           }
        );
        $('.datepicker').datepicker({
            dateFormat: 'yy-mm-dd'
        });

        var path = $('h4').text();
        console.log(path)
        if(path == '通訊錄'){
            $('li.nav-item').removeClass('');
            $('li.nav-item:eq(6)').addClass('active');}
        else if(path == '原物料訂單'){
            $('li.nav-item').removeClass('');
            $('li.nav-item:eq(5)').addClass('active');
            $('h4').css('display', 'none');}
        else if(path == '門市需求單'){
            $('li.nav-item').removeClass('');
            $('li.nav-item:eq(4)').addClass('active');}
        else if(path == '原物料庫存'){
            $('li.nav-item').removeClass('');
            $('li.nav-item:eq(3)').addClass('active');}
        else if(path == '行銷策略列表'){
            $('li.nav-item').removeClass('');
            $('li.nav-item:eq(2)').addClass('active');}
        else if(path == '顧客關係管理'){
            $('li.nav-item').removeClass('');
            $('li.nav-item:eq(1)').addClass('active');
            }
        else if(path == "行銷Dashboard"){
            $('li.nav-item').removeClass('');
            $('li.nav-item:eq(0)').addClass('active');
            $('h4').css('display', 'none');}

        {% block extra_scripts %}{% endblock %}
    });

    </script>

<style>
    a span {
        color: blue;
    }
</style>

</body>
</html>

templates/consolidated_statement.html
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>

        <!-- navigation things-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{#        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>#}
        <!-- FontAwesome -->
{#        <script src="https://kit.fontawesome.com/5dc39887b7.js" crossorigin="anonymous"></script>#}
        <!--tree things -->
{#        <link href="test.css" rel="stylesheet">#}

{#        <script type="text/javascript" src="/static/js/jquery.js"></script>#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script type="text/css">
        body {
            min-height: 100vh;
        }
    </script>
    <!--start of navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'dash_board' comp_id=comp_id %}">OurLogo</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'get_consolidated_statement_page' comp_id=comp_id rpt_id=rpt_id  %}" tabindex="-1" aria-disabled="true"><strong>合併勾稽</strong></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'get_consolidated_disclosure_page' comp_id=comp_id rpt_id=rpt_id  %}"  tabindex="-1" aria-disabled="true"><strong>附註格式</strong></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'compare_with_last_consolidated_statement' comp_id=comp_id rpt_id=rpt_id  %}"  tabindex="-1" aria-disabled="true"><strong>前期比較</strong></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <div class="other_nav_buttons">
                <i class="fas fa-cog"></i>
                <i class="fas fa-user"></i>
            </div>
        </div>
    </nav>
</head>
<body>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-sm-8" id="cash_title">現金及約當現金</div>
            <div class="col-sm-8" id="property_title" style="display:none">不動產</div>
            <div class="col-sm-2">
                <select id="selectId" onchange="ShowSelectValue()" >
                    <option value="0">現金及約當現金</option>
                    <option value="1">不動產</option>
                    <option value="2">c</option>
                </select>
            </div>
            <div class="col-sm-2"><button class="btn btn-secondary" onclick="location.href='{% url 'get_consolidated_disclosure_page' comp_id=comp_id rpt_id=rpt_id%}'">下一步</button></div>
        </div>
        <br>
        <br>
        <div id='cash'>
            <div class="row">
                <div class="col">明細資訊</div>
                {% for company in com_list %}
                
                    <div class="col-sm">{{ company}}</div>
                
                {% endfor %}
                <div class="col-sm">合計帳列數</div>
                <div class="col-sm">合併沖銷</div>
                <div class="col-sm">合計查核數</div>
            </div>


            <div class="adj-row row" style="border-bottom-style: dashed; border-bottom-color: darkgray;"></div>
            <div class="row">
                <div class="col-sm">活期存款</div>
                {% for demand_deposit in demand_deposit_list %}
                    {% if demand_deposit == 0 %}
                        <div class="col-sm">--</div>
                    {% else %}
                        {% if demand_deposit < 0 %}
                            <div class="col-sm">({{ demand_deposit|floatformat:0|intcomma:False|slice:'1:' }})</div>
                        {% else %}
                            <div class="col-sm">{{ demand_deposit|floatformat:0|intcomma:False }}</div>
                        {% endif %}
                    {% endif %}  
                {% endfor %}
            </div>
            <div class="adj-row row" style="border-bottom-style: dashed; border-bottom-color: darkgray;"></div>
            <div class="row">
                <div class="col-sm">支票存款</div>
                {% for check_deposit in check_deposit_list %}
                    {% if check_deposit == 0 %}
                        <div class="col-sm">--</div>
                    {% else %}
                        {% if check_deposit < 0 %}
                            <div class="col-sm">({{ check_deposit|floatformat:0|intcomma:False|slice:'1:' }})</div>
                        {% else %}
                            <div class="col-sm">{{ check_deposit|floatformat:0|intcomma:False }}</div>
                        {% endif %}
                    {% endif %}  
                {% endfor %}
            </div>
            <div class="adj-row row" style="border-bottom-style: dashed; border-bottom-color: darkgray;"></div>
            <div class="row">
                <div class="col-sm">定期存款</div>
                {% for foreign_currency_deposit in foreign_currency_deposit_list %}
                    {% if foreign_currency_deposit == 0 %}
                        <div class="col-sm">--</div>
                    {% else %}
                        {% if foreign_currency_deposit < 0 %}
                            <div class="col-sm">({{ foreign_currency_deposit|floatformat:0|intcomma:False|slice:'1:' }})</div>
                        {% else %}
                            <div class="col-sm">{{ foreign_currency_deposit|floatformat:0|intcomma:False }}</div>
                        {% endif %}
                    {% endif %}  
                {% endfor %}
            </div>
            <div class="adj-row row" style="border-bottom-style: dashed; border-bottom-color: darkgray;"></div>
            <div class="row">
                <div class="col-sm">定期存款（原幣）</div>
                {% for currency_cd in currency_cd_list %}
                    {% if currency_cd == 0 %}
                        <div class="col-sm">--</div>
                    {% else %}
                        {% if currency_cd < 0 %}
                            <div class="col-sm">({{ currency_cd|floatformat:0|intcomma:False|slice:'1:' }})</div>
                        {% else %}
                            <div class="col-sm">{{ currency_cd|floatformat:0|intcomma:False }}</div>
                        {% endif %}
                    {% endif %}  
                {% endfor %}
            </div>
            <div class="adj-row row" style="border-bottom-style: dashed; border-bottom-color: darkgray;"></div>
            <div class="row">
                <div class="col-sm">定期存款（外幣）</div>
                {% for foreign_currency_cd in foreign_currency_cd_list %}
                    {% if foreign_currency_cd == 0 %}
                        <div class="col-sm">--</div>
                    {% else %}
                        {% if foreign_currency_cd < 0 %}
                            <div class="col-sm">({{ foreign_currency_cd|floatformat:0|intcomma:False|slice:'1:' }})</div>
                        {% else %}
                            <div class="col-sm">{{ foreign_currency_cd|floatformat:0|intcomma:False }}</div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>

        </div>
        <div id=property style="display:none">
            <p>hi</p>
        </div>
    </div>
</body>

<script>
    $( document ).ready(function() {
        var rel_demand_deposit_list = {{ rel_demand_deposit_list|safe }};
        console.log(rel_demand_deposit_list);
        var rel_check_deposit_list = {{ rel_check_deposit_list|safe }};
        console.log(rel_check_deposit_list);
        var rel_foreign_currency_deposit_list = {{ rel_foreign_currency_deposit_list|safe }};
        console.log(rel_foreign_currency_deposit_list);
        var rel_currency_cd_list = {{ rel_currency_cd_list|safe }};
        var rel_foreign_currency_cd_list = {{ rel_foreign_currency_cd_list|safe }};
        var rel_error_alert = "";
        
        if (rel_demand_deposit_list.length>0){
            for (var step = 0; step < rel_demand_deposit_list.length; step++) { 
                console.log("!");
                rel_error_alert=rel_error_alert+"活期存款的關係人交易於公司編號"+rel_demand_deposit_list[step].com+"中，多出與公司編號"+rel_demand_deposit_list[step].target+"的交易一筆\n";
        }};

        if (rel_check_deposit_list.length>0){
            for (var step = 0; step < rel_check_deposit_list.length; step++) {
                rel_error_alert=rel_error_alert+"支票存款的關係人交易於公司編號"+rel_check_deposit_list[step].com+"中，多出與公司編號"+rel_check_deposit_list[step].target+"的交易一筆\n";
        }};

        if (rel_foreign_currency_deposit_list.length>0){
            console.log("?")
            for (var step = 0; step < rel_foreign_currency_deposit_list.length; step++) { 
                rel_error_alert=rel_error_alert+"支票存款的關係人交易於公司編號"+rel_foreign_currency_deposit_list[step].com+"中，多出與公司編號"+rel_foreign_currency_deposit_list[step].target+"的交易一筆\n";
        }};

        if (rel_currency_cd_list.length>0){
            for (var step = 0; step < rel_currency_cd_list.length; step++) { 
                rel_error_alert=rel_error_alert+"支票存款的關係人交易於公司編號"+rel_currency_cd_list[step].com+"中，多出與公司編號"+rel_currency_cd_list[step].target+"的交易一筆\n";
        }};

        if (rel_foreign_currency_cd_list.length>0){
            for (var step = 0; step < rel_foreign_currency_cd_list.length; step++) { 
                rel_error_alert=rel_error_alert+"支票存款的關係人交易於公司編號"+rel_foreign_currency_cd_list[step].com+"中，多出與公司編號"+rel_foreign_currency_cd_list[step].target+"的交易一筆\n";
        }};

        if (rel_error_alert.length != 0){
            alert(rel_error_alert);
        };
        
    });
    


    function GetSelectValue(obj) {
        var selectObj = document.getElementById(obj);
        return selectObj.options[selectObj.options.selectedIndex].value;
    }

    function ShowSelectValue() {
        var value = GetSelectValue("selectId");
        if (value==0) {
            $("#cash").show();
            $("#cash_title").show();
            $("#property").hide();
            $("#property_title").hide();
            //alert("1");
        } else if(value==1) {
            $("#cash").hide();
            $("#cash_title").hide();
            $("#property").show();
            $("#property_title").show();
            //alert("2");
        }else{
            alert("2");
        }
    }
    
    $('#next_btn').click(function(){
        $.ajax({
                url: "{% url 'get_consolidated_disclosure_page' comp_id=comp_id rpt_id=rpt_id%}",
                data: {"acc_id": $("#selectId option:selected").text()},
                type:"GET",
                success: function (response) {
                    console.log('ajax success');
                    location.reload();
                }, error: function (error) {
                    alert('Error to get datasource!');
                    console.log(error);
                }
            });
    });
</script>
</html>
 